### PR TITLE
Add ceph cluster name support for calamari-crush-location

### PR DESCRIPTION
**Pull request by zhiteng**
calamari-crush-location.py has a '--cluster' parameter but never makes
use of it. This change adds customized ceph cluster name support for
this script so that it doesn't always assume ceph cluster name to be
'ceph'.

This change also wraps long line code to less than 80 characters.

### CODE REVIEW

**Comment by zhiteng** [comment]
The CI failure doesn't seem relevant to the change I made.  How can I trigger another round of CI?

**Comment by GregMeno** [comment]
@zhiteng Thank you for contributing. In general I don't like wrapping lines for wrapping sake.

**Comment by GregMeno** [comment]
@zhiteng I would prefer to merge #357 since it seems to be the same fix minus the line-wrapping. Does that sound right?

**Comment by zhiteng** [comment]
@GregMeno #357 wasn't a complete fix.  Let me remove the wrapping for 358 and resubmit.  Thanks.

**Comment by GregMeno** [comment]
@zhiteng Looks good. Thank you

**Pull request merged**
