### PR TITLE
requirements.txt and vps_bootstrap: Update salt version to 2015.5.1

### PR DESCRIPTION
**Pull request by joehandzik**
Update 2.7 requirements file and vps_bootstrap.sh to point to 2015.5.1 salt version.

### CODE REVIEW

**Comment by joehandzik** [comment]
My only question here...do you want me to update the 2.6 requirements.txt file, or should we leave 2.6 alone? I vote to leave 2.6 alone for now, but I can see reasons for updating it too. It's an easy addition to the pull request, just let me know what you want.

**Comment by joehandzik** [comment]
And, of course, you'll want to accept the other pull request before accepting this one. This build will continue to fail without those changes.

**Comment by GregMeno** [comment]
for some reason I forgot about https://github.com/saltstack/salt/issues/24613
which is causing the ForbiddenYeild issue in https://github.com/ceph/calamari/issues/309

Options for that are likely to releax the nosleep decorator in some way. TBD.
Thoughts?

**Comment by joehandzik** [comment]
Yeah, that's the only thing that makes sense to me in the short-term. Lemme read a little bit more so my opinion is more...informed.

As a side note, I find it fascinating that the discussion on the ceph-calamari list mentioned that this patch (https://github.com/alexm/calamari/commit/09e39b50dffac58c9ab6b10dd643c4b0e5dc2552) improved the situation. All that should have done is break the _create_loader call. Maybe breaking _create_loader somehow dodges a case that causes the ForbiddenYield?

**Comment by joehandzik** [comment]
It would have been nice if this patch (https://github.com/saltstack/salt/blob/7c537cd9ece84adedce45e8da371a08f21291a25/salt/utils/event.py) at least provided an override for that behavior. 

Is it naive to think that we could just wait a second before taking the yields as a serious problem?

Out of curiosity, is the decorator present because the "subtle bugs" mentioned here (http://ceph.com/calamari/docs/development/cthulhu_locking.html#the-nosleep-decorator) have been observed in some way?

Another option would be to put locking back in for a time, at least until salt can guarantee the assumptions you've described. See this comment: (Add gevent_util.nosleep to enforce areas that shouldn't sleep and therefore aren't required to take locks) here: (https://github.com/ceph/calamari/commit/6261ac307cd23548c8dcec67997469ad4aa338ea)

**Comment by GregMeno** [comment]
@joehandzik https://github.com/saltstack/salt/pull/23236 is what they are considering to remove the hack.

Waiting a second seems like the wrong solution. I was thinking more like we just log it as an error instead of throwing an exception.

As far as observed subtle bugs I don't remember catching any.

**Comment by joehandzik** [comment]
Geez that's a heavy pull request, I'll take a look when I have a little more time. 

I think that logging the error instead of throwing the exception is fine, as long as no catastrophic issues have been detected from the context switch that the decorator is trying to ensure isn't happening.

**Pull request merged**
