### PR TITLE
Add db_port config to calamari_web settings

### PR DESCRIPTION
**Pull request by wyllys66**

### CODE REVIEW

**Comment by GregMeno** [comment]
@wyllys66 This fix looks pretty good. Would you please rebase it into one commit and add the 
Signed-off-by: {name} {email}
?

**Comment by wyllys66** [comment]
Rebased and ready to go, thanks!

**Comment by dmick** [comment]
Totally a nit, but the signature should come at the bottom, and the email address should include the <>, like this commit:  https://github.com/ceph/calamari/commit/df9a05ce24750ca5c1adba196bbd7b9e0ea4c199

**Comment by wyllys66** [comment]
ok, I amended the commit msg.

**Pull request merged**
