### PR TITLE
Various fixes to avoid salt

### PR DESCRIPTION
**Pull request by b-ranto**
This patchset contains a couple of fixes for the issues I noticed while testing salt-less deployment of calamari.

### CODE REVIEW

**Comment by andrewschoen** [comment]
This all looks good, but I just had a couple questions.

1. Is it true that the ``1.5`` branch does not use postgres anymore? This makes it look like we're using sqlite now https://github.com/ceph/calamari/commit/388f185f5cfbc1003a945f5112aa1e934cb5b3b0

2. Should we also delete the ``*.sls`` files from ``salt/local``?

3. Did you test deployment with the ``stable-2.2`` branch of ``ceph-ansible``?  The ``ceph-agent`` role still seems to configure salt and start services. For example, https://github.com/ceph/ceph-ansible/blob/stable-2.2/roles/ceph-agent/tasks/start_agent.yml

**Comment by ChristinaMeno** [comment]
@andrewschoen looks like I forgot that I removed all the postgres stuff a year ago. It's been shipped that way so it likely works. As far as ceph-ansible-stable-2.2 it's a good question. I don't know

As for 2. We don't need to remove all the .sls files in this PR that can wait

**Comment by andrewschoen** [comment]
@GregMeno I discussed with @b-ranto and ceph-ansible ``stable-2.2`` should work fine. My only question was concerning the tasks in ceph-ansible that ensure that ``salt-minion`` is running. @b-ranto explained that storage console will still be needing salt for their own usage, so I believe those should stay in place.

I think this is good to go.

**Comment by b-ranto** [comment]
I have tested deployment with stable-2.2. It was able to deploy calamari fine, no salt was installed on any of the nodes.

**Pull request merged**
