### PR TITLE
Fix build-rpm.sh spec

### PR DESCRIPTION
**Pull request by jameshilliard**
Adapted from [here](https://github.com/ceph/ceph-build/blob/master/calamari/build/build_rpm).

### CODE REVIEW

**Comment by GregMeno** [comment]
@b-ranto Would you please take a look at this?

**Comment by b-ranto** [comment]
This does make sense since we changed the spec file format.

**Comment by ktdreyer** [comment]
`"_unpackaged_files_terminate_build 0" ` welp

**Comment by b-ranto** [comment]
@ktdreyer that might be true but it is definitely a progress from a build script that fails because there is no calamari.spec

**Comment by ktdreyer** [comment]
@b-ranto definitely!

**Pull request merged**
