### PR TITLE
Corrected the return value issue with script run_travis.sh

### PR DESCRIPTION
**Pull request by shtripat**

### CODE REVIEW

**Comment by GregMeno** [comment]
@shtripat  @r0h4n I'm not too sure what the intent of the PR is. Perhaps we should discuss it. Surely this does more than change a return code on run_travis.sh

**Comment by shtripat** [comment]
I feel by mistake sent it ot ceph/calamari. Intended to be sent to Tendrl/ceph_bridge.
@r0h4n I feel its merged there in Tendrl/ceph_bridge.

**Comment by r0h4n** [comment]
I don't get it why this PR was opened on Ceph/calamari,  @shtripat please explain

**Comment by r0h4n** [comment]
Aha. Please close this PR

**Comment by shtripat** [comment]
Closing as it was sent by mistake.

**Pull request closed without merging**
