### PR TITLE
minion-sim: Fix minion attribute error

### PR DESCRIPTION
**Pull request by joehandzik**
Signed-Off-By: Joe Handzik <joseph.t.handzik@hp.com>

### CODE REVIEW

**Comment by joehandzik** [comment]
Addresses https://github.com/ceph/calamari/issues/320

**Comment by joehandzik** [comment]
Looks like the file itself in the saltstack github has only existed since very late 2014...so I'm assuming I need what you suggested.

https://github.com/saltstack/salt/commits/develop/salt/cli/daemons.py

I'll update in the morning.

**Comment by joehandzik** [comment]
@dmick, the issue you pointed out has been addressed. Thanks for taking a look!

**Comment by dmick** [comment]
LGTM.  @GregMeno I'll leave it to you for final but it looks right and safe to me now.

**Pull request merged**
