### PR TITLE
devmode: pin to a specific version of salt

### PR DESCRIPTION
**Pull request by GregMeno**
Updated docs to reflect the new process

Signed-off-by: Gregory Meno <gregory.meno@inktank.com>

@dmick

### CODE REVIEW

**Comment by dmick** [comment]
Motivation?  This means we have no early warning...

**Comment by dmick** [comment]
Motivation?  This means we have no early warning...

**Comment by joehandzik** [comment]
I kinda figured this would be the case, but these changes fixed the problems I ran into today (half the calamari build was broken when running the vagrant devmode build on both Centos7 and OSX Yosemite). Looks like something broke in the latest SaltStack version for a lot of people. For those of us still trying to wrap our heads around the various Ceph repos, nailing down stable versions of supporting components is worth the lack of early warning.

**Comment by joehandzik** [comment]
FYI, this change doesn't quite work behind a proxy. If you add -G to the install_salt.sh call on line 5, everything is hunky dory (forces https:// instead of git://. git:// is the bane of existence behind the HP firewall).

**Comment by GregMeno** [comment]
@joehandzik good to know. I will add that. I plan to check 2014.7.0 since that is the stable release. 2014.7.1 was failing on me, if it passes that I'll likely merge this. Either way it going upstream as an issue tomorrow

**Comment by joehandzik** [comment]
Hmmm, interesting. I ran into a funny problem when I tried to port this sort of change over to calamari-clients/romana, v2014.1.13 seems to be missing a jinja API call that is made in the “setvars” salt script (the call at the very top of the file). I’ll poke around when I have time and see if the versions you’re talking about fare better.

Joe

**Pull request merged**
