### PR TITLE
Add release nmber 7.0.1406 vor centos 7

### PR DESCRIPTION
**Pull request by TheMeier**

### CODE REVIEW

**Comment by ktdreyer** [comment]
I think the general idea here is sound, and thank you for the pull request!

Regarding the specific implementation, we'll want to use `cut` to modify the `VERSION` definition to only have the major `"6"` or `"7"` release number instead. Would you mind amending your patch to do that, and then re-pushing to this branch?

While you're amending you can also change `nmbr` to `number` and `vor` to `for` in the commit log.

(CC'ing @branto1 in case he wants to review.)

**Comment by branto1** [comment]
Actually, we can do something simpler here, we can simply use the matching mechanism that case in bash provides. i.e. we can do:
case $VERSION in
  7.*) <stg>
  6.*) <stg>
...

**Comment by branto1** [comment]
I've sent out the pull request https://github.com/ceph/calamari/pull/251 with the fix that I mentioned above.

**Comment by GregMeno** [comment]
handled in #254

**Pull request closed without merging**
