### PR TITLE
wip-centos7-build

### PR DESCRIPTION
**Pull request by ksingh7**
With this pull request i am sending the following changes
- Calamari-server RPM package build for CentOS7. There has been dependencies on some packages that is not allowing CentOS6 vagrant box to build packages for CentOS7. For this reason i have created a new vagrant box profile for CentOS7-build.

- Changes in this pull request includes
  - 3 updates in `calamari/vagrant/centos7-build/salt/roots/build_deps.sls` which are required specifically by CentOS7
      - zeromq3-devel      ( Read the thread : https://github.com/ceph/calamari/commit/12cdabd773accf14b13c06d5d42291047733e201 )
      - selinux-policy-devel    (failure logs : http://paste.ubuntu.com/11725262)
      - selinux-policy-doc     (failure logs : http://paste.ubuntu.com/11725073)

- Minor change in Vagrantfile
   - updated vagrant box information ```config.vm.box = "boxcutter/centos71"``` (https://github.com/ceph/calamari/commit/12cdabd773accf14b13c06d5d42291047733e201)

- Directory name of vagrant/centos-build has been changed to vagrant/centos6-build
   - So the users should not get confuse between CentOS6 and CentOS7

All of these changes has been tested and verified , you can refer the logs at 

success logs : http://paste.ubuntu.com/11725052

Kindly merge these changes with the relevant branch

### CODE REVIEW

**Comment by ksingh7** [comment]
@GregMeno do you got my pull request for code review / merge. The Travis CI build failed for some reason.  Could you help in this.

**Comment by joehandzik** [comment]
2.03s$ make lint
target: lint
echo "Checking code style:" && \
		flake8 cthulhu/ --ignore=E501,E402,E731 &&\
		flake8 rest-api/ --ignore=E501,E402,E731 &&\
		flake8 calamari-common/ --ignore=E501,E402,E731 &&\
		flake8 calamari-web/ --ignore=E501,E402,E731 &&\
		flake8 tests/ --ignore=E501,E402,E731 &&\
		flake8 salt/srv/salt/ --ignore=E501,E402,E731 &&\
		echo "OK"
Checking code style:
cthulhu/cthulhu/calamari_ctl.py:180:1: E302 expected 2 blank lines, found 1
cthulhu/cthulhu/calamari_ctl.py:191:1: E302 expected 2 blank lines, found 1
make: *** [lint] Error 1

You failed a code style test. Run 'make lint' on your source directory to see these errors.

**Comment by joehandzik** [comment]
Though, I see what you're saying now...it doesn't look like your changes should have caused those failures.

**Comment by dmick** [comment]
I updated 1.3 and master to remove the pep8 issues in calamari_ctl.py; please rebase, Karan, and then you should get a clean Travis run

**Comment by ksingh7** [comment]
@dmick thanks , i did rebase and now Travis CI executed cleanly. Could you merge this with calmari code.

**Pull request merged**
